### ISSUE TITLE
"Help" link leads to Github Pages 404

### ISSUE THREAD

**Issue by alizehctl** [soapdog/little-webby-press#8]
https://little.webby.press/help leads to a 404

![image](https://user-images.githubusercontent.com/31581044/114512925-0f6dba00-9c53-11eb-88b0-2d73df12e627.png)

**Comment by soapdog** [comment]
I haven't created the docs yet because the UI is still in flux.

**Comment by soapdog** [comment]
The documentation is now working. The link changed to `/documentation/en` because I plan to add localised docs in the future.
